### ISSUE TITLE
Plot for my config is too simple...

### ISSUE THREAD

**Issue by dimaqq** [ze-phyr-us/tcviz#2]
Here are my sample rules:

```
tc qdisc add dev eth0 root handle 1: htb default 9
tc class add dev eth0 parent 1: classid 1:2 htb rate 1mbit
tc qdisc add dev eth0 parent 1:2 fq_codel ecn
 
tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip dst 10.0.2.7/32 classid 1:2  # every Egnyte ip address
tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip dst 10.0.2.8/32 classid 1:2
# no rules for 1:9, other traffic is unlimited
```

And here's the tool's output:

![eth0](https://cloud.githubusercontent.com/assets/662249/12679019/15c6962e-c6a2-11e5-94d6-e351f1047939.png)

I would expect to see:
* other (unmatched) traffic for default `classid 1:9` via rule `handle 1: htb default 9`
* those `back` solid arrows you have in your example.png

**Comment by ze-phyr-us** [comment]
Hi Dima, I unfortunately no longer work with tc and do not maintain this tool. If you decide to fix this yourself, I am always happy to accept a PR!
