### ISSUE TITLE
Change the env from python to python3

### ISSUE THREAD

**Issue by nikolavp** [ze-phyr-us/tcviz#5]
Awesome tool - although simplistic, it saved me some time while debugging what was not properly setup in my configuration. 

Just change the shebang because it didn't run on my Ubuntu machine. I had to 

```
-#!/usr/bin/env python
+#!/usr/bin/env python3
```

otherwise it's giving

```
  File "./tcviz.py", line 43
    print('Usage: %s <interface>' % sys.argv[0], file=sys.stderr)
                                                     ^
SyntaxError: invalid syntax
```

**Comment by ze-phyr-us** [comment]
Fixed, thanks!
